### ISSUE TITLE
Endpoint to create room

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate-Backend#12]
1. Get room details like name, description, metadata etc. from the request
2. Generate and sign the JWT token associated with user’s email and room_name with room_admin set to true - Use LiveKit SDK
3. Post data to LiveKit’s CreateRoom Endpoint using the token.
4. Create room on Firebase Firestore
5. Forward the response along with token

**Comment by GeniusNirmit** [comment]
Is this issue still open?

If so, then I would like to contribute...

**Comment by chandansgowda** [comment]
@GeniusNirmit This issue is open for gsoc contributors only. Feel free to check out bugs and improvement issues. You can also test the app and raise issues for bugs or improvements.
