### ISSUE TITLE
Anonymity in match_making cloud function

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate-Backend#39]
As of now, the user is considered to be anonymous even if the user chooses to use his identity in pair chat. We should now add the logic to check if the user wants to reveal his identity and make necessary changes in the database design and on client side.

**Comment by kirtanchandak** [comment]
can I take this issue?

**Comment by chandansgowda** [comment]
Yeahh sure @kirtanchandak

**Comment by kirtanchandak** [comment]
I am setting up the resonate backend on my local machine. 

I have a doubt between LIVEKIT_HOST and LIVEKIT_SOCKET_URL in the env file. 

The url that we get in dashboard is socket url I guess, where can we get he host?

**Comment by chandansgowda** [comment]
@kirtanchandak  Both are the same. Socket url will have wss:// and host will have https://

**Comment by ShamanthOP** [comment]
@chandansgowda If it's still open, I'd like to take this up.

**Comment by ShamanthOP** [comment]
@chandansgowda Should users choosing to disclose their identity be matched exclusively with others who also opt for identity disclosure, or should they be paired with everyone, regardless of identity disclosure preferences?

**Comment by chandansgowda** [comment]
Yes. Anonymous users should be matched with anonymous users only. @ShamanthOP
