### ISSUE TITLE
Cloud function to delete inactive rooms and active pair chats

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate-Backend#43]
Sometime due to some inconsistency, the room might be still available on the database even if no one is in the room. Let's delete these using a scheduled cloud function.

**Comment by Jyoticharan** [comment]
please provide the description regarding the issue I want to work over it and please assign me the issue

**Comment by Suraj-Dhankad2025** [comment]
@chandansgowda in which file i have to make the function to delete the inactive rooms and active pair chats can you provide some context regarding the issue

**Comment by chandansgowda** [comment]
@Suraj-Dhankad2025 You will have to add a new appwrite cloud function. DM me on appwrite to get access for our appwrite project instance.

**Comment by Suraj-Dhankad2025** [comment]
DM on appwrite?

**Comment by chandansgowda** [comment]
@Suraj-Dhankad2025 On discord.

**Comment by ShamanthOP** [comment]
Hey @chandansgowda assign this to me

**Comment by ShamanthOP** [comment]
@chandansgowda Tried to reproduce the issue seems like the livekit webhook receiver function takes care of this issue

**Comment by Aarush-Acharya** [comment]
Hey @ShamanthOP, I believe this is already Implemented and the issue is out of context now 

Thank you for your time
