### ISSUE TITLE
Migrate Resonate API to Appwrite Cloud Functions

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate-Backend#54]
There are three api endpoints to create, join and delete rooms. These can be migrated to appwrite cloud functions. Also make necessary changes on the flutter's side.

**Comment by ShamanthOP** [comment]
@chandansgowda I'd like to take this up.

**Comment by chandansgowda** [comment]
- [ ] Create Cloud Functions from existing endpoints and controllers
- [ ] Deploy it to appwrite and test
- [ ] Make necessary changes in flutter app
- [ ] Test the whole application
- [ ] Remove the files which are no longer required
