### ISSUE TITLE
docs: update readme for seamless transition after migration

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate-Backend#59]
Following the successful migration of the project to cloud functions, it is crucial to update the project's README to provide comprehensive and accurate guidance for developers. This issue encompasses revising the README with the most current and pertinent information, highlighting changes in architecture, setup instructions, and other relevant details to ensure a smooth transition and continued development in the cloud functions environment.

**Comment by ShamanthOP** [comment]
@chandansgowda I'll take this up.

**Comment by chandansgowda** [comment]
Any updates @ShamanthOP ?

**Comment by ShamanthOP** [comment]
Working on it. I'll complete it tomorrow
