### ISSUE TITLE
Making utilities like ApiError , ApiResponse.

### ISSUE THREAD

**Issue by Ayush-Vish** [AOSSIE-Org/Resonate-Backend#62]
Make these utilities class will Modularized the overall code.

**Comment by Ayush-Vish** [comment]
@varunchitre15  @saisankargochhayat   Can I contribute in this project ?

**Comment by Aarush-Acharya** [comment]
Hey @Ayush-Vish, can you please elaborate on your use case I feel the error handling is done well now. But if you feel anything more of value could be added to it please let me know
