### ISSUE TITLE
Setup LiveKit Server SDK for JS

### ISSUE THREAD

**Issue by chandansgowda** [AOSSIE-Org/Resonate-Backend#9]
LiveKit SDK is used to manage [LiveKit](https://livekit.io/) rooms and create access tokens from JavaScript/Node.js backend. This has to be added to the project.

**Comment by chandansgowda** [comment]
Know more here - [LiveKit SDK for JS](https://github.com/livekit/server-sdk-js)

**Comment by SimardeepSingh1450** [comment]
@chandansgowda please assign me this issue, so that i can start working on it.

**Comment by chandansgowda** [comment]
@SimardeepSingh1450 You can work on it and send in a PR.

**Comment by chandansgowda** [comment]
Any update @SimardeepSingh1450  ?

**Comment by SimardeepSingh1450** [comment]
@chandansgowda Currently learning more about webrtc, will soon come to livekit docs, will let you know

**Comment by chandansgowda** [comment]
Hey @SimardeepSingh1450 
This has to be setup by this week. I will take this up for now. Please feel free to suggest performance and structure improvements. You can look into other issues if you are interested.
